services:
    database:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD?Missing postgre password}"
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
    devcon:
      build:
        context: .
        dockerfile: build/Dockerfile
      environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD?Missing postgre password}"
        POSTGRES_HOST: "database"
      ports:
        - "4000:4000"
volumes:
  postgres_data: